"""
Django settings for GiftcardSite project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import base64

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# Use a valid default Fernet key for CI/test environments.
# Strip whitespace/newlines in case the value comes from CI or .env formatting.
DEFAULT_FERNET_KEY = "N9fs6lGUnaVLerAcAx8pwYgig-K_1A9aYkhGE1qu_Jo="
RAW_FERNET_KEYS = os.environ.get("FERNET_KEYS", DEFAULT_FERNET_KEY).strip()

# Support either a single key or a comma-separated list of keys.
FERNET_KEYS = [key.strip() for key in RAW_FERNET_KEYS.split(",") if key.strip()]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow hosts from environment when running in Kubernetes.
ALLOWED_HOSTS_ENV = os.environ.get("ALLOWED_HOSTS", "").strip()
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(",") if host.strip()]
else:
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom
    'LegacySite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GiftcardSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GiftcardSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static Images
IMAGE_ROOT = os.path.join(BASE_DIR, 'images')

# JS Root
JS_ROOT = os.path.join(BASE_DIR, 'templates', 'js')

# CSS Root
CSS_ROOT = os.path.join(BASE_DIR, 'templates', 'css')

# Font Root
FONT_ROOT = os.path.join(BASE_DIR, 'templates', 'fonts')

# Random Seed for testing
RANDOM_SEED = base64.b64decode("2RUHYAyJWdDdXOicZfnTRw==")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/vol/web/static'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/vol/web/media'

# Auth Backends
AUTHENTICATION_BACKENDS = ['LegacySite.models.OurBackend']

# Django 3.2 compat
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# ShoddyCorp note: hack to get around stupid browser restrictions.
# Fixes issue with Chrome not allowing partner sites to access the site.
SESSION_COOKIE_SAMESITE = 'Lax'
# Don't know if this is necessary but all this stupid security stuff just
# makes my job harder
SESSION_COOKIE_HTTPONLY = False

# DO NOT delete line 156-158, this is for using Django/Gradescope integration
# Also used for my own testing of autograder
RUN_GITHUB_ACTIONS = os.environ.get('GITHUB', 'no')
if os.path.exists('/autograder/results') and os.path.isdir('/autograder/results') or RUN_GITHUB_ACTIONS == 'yes':
    TEST_RUNNER = 'GiftcardSite.gradescope_django_runner.GradescopeDjangoRunner'