---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: django-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCf2Ae8gFogzBPBHZBTGaqjEsygncNgA5I3WdH/IYA1mVL5Stq5ZTpoQO3W75zkUREMYXU3ijCdR/+yCWb1ILzG9IEmrsVZ6h+ZP2+nUaJvf7bN5sT2cQ6nPb+geWVP1Dypoj+tfFTGTRjn2tnKqKIF4ttV5k4yOs6XJM4/ReN3/+OT910qdfts5dQMjIYcjm/h0MjWSB0GS22l5dL+6YYrMn7kIv2kqcRZUdXTakaPHegNPBG56zzxb/MADU6HXX19S+i+sPWsIMHY0KiPFlJeAnua3Rb4KJd92NZkgupdkMwyXG0m6w1zAS7CQzLgdGZdFmY1Z2qAD5MXM5Qmj6xIEMdyxDXSeDZuoRjgLDp+lmPZ4IrP3xaVIjcV+VUhFEDVahIzjOVcikt0eELK/CqGExKdZzjgwrlloF0YaBVJpRNBypnjOI3v8mHZi/yqhiiFP5CyTIrtru3AyZ+XbH591LHwn9fE86uVAFewQeUuVTFsDBOCs0eCDmZ5o0fiVuuBaIMvOIt7k5686s/gO13QWQViXkQeyu7VWmsC7ZdrnF1vSN6MY8dEcfNAEMM6QzPBNgcWOP0xcMLXofiaNr/tceud1hfWi3kIVr62b4EtQfQIdJQvSX2TbJm1NIHPjTWCWlf2M7oF5vGb1+KfmsvtNA7i8f2MwSlURPl8gn6TnpUPcLixWXd/+Sa7BubTYK42Q6wjq5ya3zvbtq5FuLcwEA==
    SECRET_KEY: AgC9NQMhD1/tUeFtLDUcpi234SRLK3LcQDLaBQlnEFGSb45BDCuSRUCXrHER4M44454f2UzOs2mCdn7WBKeYOwXpLqKmF6c0FZecLMvx7oPWpppcsFXo/P7HR1RrbgEWaTm7XB0hE9RpeeIqGcMmHP4jSO1f+Qs6LQVzZ6j3un96QsrB1XH89jxm1/mbozR8CacfYXmlaIx/MbtsN+VoaM8zz/mvUVkYimwsxtYE252j98DBL0qLHeLyctcOSsk1Sv2feZN80Ov39k2IwylOjyP83HnApsly6REY3YAnsNpIWVhdYd7OqYOncLDHhTV4tVjiAivxV9S+rT8mCkPmOjXhlR6mNw8pOwXae67kG+cQdh8CmQk0IkS6/Y57/kfFeX1ud2yuo3G6JBeik7GVSykOFZipLBDnd5BRzpvaAflbBfsipRZtsKcyDH4cOVh5vqEqFpldhyoWWIEkGNtXO5J552CnfYYk2IyQvxt5qyrzhyAEMVfAACey4lx8VcUL2RzeyDW+1dcFWVejoI7vcjpeT+/p4KPAdp3YDC2CtF/ovHlRZXKg6CYCNGPatG+bRdLH/vJG0XEdw61OD1nMurJUwuyTzU3kJ5WoevS9oxf9/f2mKI5bbwK8aZtOl3o4uwwbqHCegoI/K8KoC1O+uSdNwwNt/X3w3drBZLXX7l69hbtgN2xLLRdLW4yKzpc8X5ZSFe7/DKv6s2+N+O0NC841SWbnjgLMoM8IIZwV6gJhHBct7Kc/xYi9peBq2olWyAqK4eLussotuT3rmOsuWQyB2VLJ
  template:
    metadata:
      name: django-secret
      namespace: default
    type: Opaque
